# server port config
server:
  port: 8404


# driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/notfound
    username: notfound
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 10MB
      location: C:/thymeleaf-springboot/
#      location: /Users/sooyeun/Desktop/dev/404NOTFOUND/fileupload
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true
    web:
      resources:
#        static-locations: C:/not404foundImageFile/
        static-locations: C:\dev\NF404\SemiProject404NotFound\not404found\src\main\resources\static\images\product
#        static-locations: /Users/sooyeun/Desktop/dev/404NOTFOUND/fileupload

image:
  image-dir: img

summernote:
  image-dir: /Users/sooyeun/Desktop/dev/404NOTFOUND/fileupload/

# mybatis config
mybatis:
  mapper-locations: mybatis/mappers/*.xml
  # alias Setting
  type-aliases-package: com.nf.not404found
  configuration:
    map-underscore-to-camel-case: true